version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="fumi042's server"
      - WORLD="fumi042"
      - PASSWORD="SECRET_VALHARA"
      - TZ=Asia/Tokyo
      - PUBLIC=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="* */1 * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
    volumes:
      - ./valheim_dh/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim_dh/server:/home/steam/valheim
      - ./valheim_dh/backups:/home/steam/backups